### PR TITLE
654:Fix intermittent UI failures

### LINKED ISSUE #654: UI Tests - Fix tests failing on Bitrise scheduled build
Even though tests were green in the PR, when running them in the [scheduled build ](https://app.bitrise.io/build/c8c175f9bd143e6c)(daily) there are still some intermittent failures. 
Before running tests on PR or more frequently lets try to have them totally stable.

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #654 

Some changes to try to get tests passing 100%
testDisconnectDisclaimer is failing now trying to find the `Disconnect Firefox Lockbox` string, I have changed it so that test looks for the Disconnect button instead

### CODE REVIEW

**Comment by isabelrios** [comment]
Tests run three times in a row in bitrise, all green...asking for r? 
Hopefully with these changes scheduled master build will be green too 🤞

**Comment by devinreams** [comment]
Odd, the daily run did not succeed on `testDisconnectDisclaimer` and `testFxALogin` it seems:
https://app.bitrise.io/build/07539787768e8db5

**Comment by isabelrios** [comment]
> Odd, the daily run did not succeed on testDisconnectDisclaimer and testFxALogin it seems:
https://app.bitrise.io/build/07539787768e8db5

You are right on master both are failing now but I run this build several times and they both passed... I think the testDisconnectDisclaimer was failing due to it was not finding the string, I changed to look for the button instead to see if that way it is more stable...and it was causing the next failure in the testFxALogin...

**Comment by devinreams** [comment]
Sorry for this @isabelrios but to keep the rebrand and localization work on track we merged that PR and have a conflict with your branch here now. 😔

**Comment by isabelrios** [comment]
> Sorry for this @isabelrios but to keep the rebrand and localization work on track we merged that PR and have a conflict with your branch here now. 😔

Oh no worries! I can fix that easily. The priority is what matters :)

**Comment by devinreams** [comment]
Updating against `master` once more to make sure this passes.

Then will merge and see if the daily UI tests pass OK (they should!). 😁

**Comment by devinreams** [comment]
OK I manually ran the "testing-enable-ui-tests" workflow and it worked against this branch:
https://app.bitrise.io/build/15a99b7ba5997752

image


Let's merge!

**Pull request merged**
