### PR TITLE
1035 - Handles and context menus have solid backgrounds instead of transparent

### LINKED ISSUE #1035: Search bar text handles have violet background
## Steps to reproduce

1. Login
2. Tap search icon on top right
3. Make text handle appear by tapping and holding in search field

### Expected behavior

Text handle drawable shows up with appropriate accent color and transparent background

### Actual behavior

Text handle drawable shows up with default android holo color and a background matching it's parent

### Device & build information
* Device: Present on Galaxy S8 & Nexus 5X android emulator
* Build version: ?
### Notes
Attachments: 
image

### PR DESCRIPTION
**Pull request by lucacataldo**
Fixes #1035, #701 

Connected to #1014 , #298 

## Testing and Review Notes

It turns out issues related to UI elements having odd backgrounds / borders (text selection handles, copy/paste menus & text pointers included) stem from the fact that the root App Theme sets a value to android:background (@color/background_white in this case). This appears to be applied to ALL child elements which includes various context menus and selection elements that should otherwise have a transparent background. Manually setting styles on EditText elements does not fix this issue as the parent theme background setting overrides any style set.

Instead, another style is used (EditTextHandlesReset) as a theme on the EditText objects in order to reset any parent theme background settings. This, however, does not fix copy/paste long press menus (#1014). For this we must set the root background to transparent and adjust backgrounds manually.

This seems like more of an android bug but the "it works"<sup>TM<sup>

Tested on S8 & various emulators. 

Lint Errors:

Overdraw errors occur, not sure how to fix if someone could help

## Screenshots or Videos

before:

lockwise_handle

after:
image

## To Do

- [X] double check the original issue to confirm it is fully satisfied
- [X] add testing notes and screenshots in PR description to help guide reviewers
- [X] add unit tests (N/A)warnings
- [X] request the "UX" team perform a design review (if/when applicable)
- [X] make sure CI builds are passing (e.g.: fix lint and other errors)
- [X] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by eliserichards** [comment]
Hi @lucacataldo! This looks great! I'm super impressed with all of the work you put into this. I am going to take a look at the overdraw errors and see what I can do. I'd love to give you credit for this and have you land it, so hopefully we can work out a patch that you can push to your branch. 

I'll update here once I have a chance to look at it 😄

**Comment by lucacataldo** [comment]
Thanks @eliserichards appreciate it! 😁

**Comment by eliserichards** [comment]
Hi @lucacataldo! I made a new commit to fix the overdraw lint errors that we were seeing on your branch (FWIW I found [this video](https://www.youtube.com/watch?v=T52v50r-JfE) informative). I made a new branch (`1035-white-backgrounds`) and opened a temp PR so you can see the commit. 

Would you like to either cherry-pick that commit into your branch or copy+paste the changes? (whatever works best for you)

Once you do that we can run all of the tests again and hopefully everything will be green! ✅ 🚀 

image

image

**Comment by lucacataldo** [comment]
Thanks for all the help & guidance @eliserichards . You rock! 😃 🥇

**Comment by eliserichards** [comment]
Just so you know, there's some weirdness going on with our CI (Bitrise) and the builds are red.. I reverted this PR temporarily but as soon as I can figure out what's wrong with master I'm going to merge it back again. Sorry!!! 😖

**Comment by eliserichards** [comment]
Hey @lucacataldo! Apparently the issue with Bitrise was their fault (they merged a commit that cast the `versionCode` (int) to a string instead of converting it. [Yay opensource tools!](https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/issues/16)) and they released a fix this morning. 

I would like to merge your code back now that our `master` is green again 😄 Would you be able to open a new PR for me that's identical to this one?

**Comment by lucacataldo** [comment]
Hey @eliserichards no worries whatsoever. Will put up a PR right now, glad i didn't break everything 😆

**Pull request merged**
