### PR TITLE
692-initial-screenshots-setup

### LINKED ISSUE #692: Initial screenshots environment
I guess that at some point we will need to automatically get the screenshots from the app. 

I have started to investigate this using [Fastlane](https://docs.fastlane.tools/actions/screengrab/)
So far I got the screenshots locally but would need more work to have it in the CI. 

If it is something you prefer to do with another tool let me know. Also if you are not thinking about having something like this :)
Thanks!

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #692 (at least temporary to get the screenshots from the repo but launching them from command line, not automatically on CI yet)

### CODE REVIEW

**Comment by isabelrios** [comment]
Is there a place where I could document how to get the screenshots? It may be nice to have the steps needed, very simple but at least to document it...

**Comment by eliserichards** [comment]
I think it would be nice to have that process in a document in the `lockwise-android/docs/` folder @isabelrios

**Comment by isabelrios** [comment]
> I think it would be nice to have that process in a document in the `lockwise-android/docs/` folder 

Thanks @eliserichards! I will create a new document for putting all this info together :)

**Comment by isabelrios** [comment]
@eliserichards so, not sure what to do here, Bitrise is red due to a lint error: 
```
  Errors found:
  
  /bitrise/src/app/src/debug/AndroidManifest.xml:22: Error: <uses-permission> tag appears after <application> tag [ManifestOrder]
      <uses-permission android:name="android.permission.DISABLE_KEYGUARD"/>
       ~~~~~~~~~~~~~~~
  /bitrise/src/app/src/debug/AndroidManifest.xml:30: Error: Permission is only granted to system apps [ProtectedPermissions]
      <uses-permission android:name="android.permission.CHANGE_CONFIGURATION"/>
```

but if I modify that file, adding that permission inside application tag the build fails to compile...how could I fix that? Thanks! :)

**Comment by eliserichards** [comment]
I will take a look at your branch @isabelrios :)

**Comment by isabelrios** [comment]
> I will take a look at your branch @isabelrios :)

Thanks @eliserichards! Small update here, now there is only one error given by lint: 

```
  /bitrise/src/app/src/debug/AndroidManifest.xml:18: Error: Permission is only granted to system apps [ProtectedPermissions]
      <uses-permission android:name="android.permission.CHANGE_CONFIGURATION"/>
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We need that line in the manifest so that the language is changed but looks like lint does not like it :/

**Comment by isabelrios** [comment]
The build is red after merging to master due to a unit test failure:
```
> Task :app:testDebugUnitTest
mozilla.lockbox.store.DataStoreTest > receiving background actions when unlocked FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at DataStoreTest.kt:243
```

This failure is affecting also latest [master](https://app.bitrise.io/build/ac158e3f0863c353), so it is not something related to this PR...

**Comment by isabelrios** [comment]
Looks like that unit test is failing intermittently, after re-running the build, it worked...

**Comment by isabelrios** [comment]
Thanks for your review @eliserichards! I can't merge, so please whenever you have a moment and if you think is ready, please merge it :) Thanks!

**Pull request merged**
