### PR TITLE
Upgrade compile and target SDK to 29

### LINKED ISSUE #1241: Upgrade to Android SDK 29
To be able to update Lockwise on the Google Play Store, we need to update both `compileSdkVersion` and `targetSdkVersion` to `29`. A quick try in PR #1240 shows that this results in a number of deprecation and compile errors that we need to get past first.

Please take a look at the [Contribution Guidelines](https://github.com/mozilla-lockwise/lockwise-android/blob/master/docs/contributing.md) if you are interested in helping out with this issue.

### PR DESCRIPTION
**Pull request by jonalmeida**
Fixes #1241

## Testing and Review Notes

~I wasn't able to test these changes but I wrote some tests or fixed the ones that mattered.~ I did some testing but a round of QA for this with varying network connectivity would be great.

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [x] double check the original issue to confirm it is fully satisfied
- [x] add testing notes and screenshots in PR description to help guide reviewers
- [x] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [x] request the "UX" team perform a design review (if/when applicable)
- [x] make sure CI builds are passing (e.g.: fix lint and other errors)
- [x] check on the [accessibility](https://mozilla-lockwise.github.io/lockwise-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by jonalmeida** [comment]
cc: @st3fan

**Comment by jonalmeida** [comment]
The PR is only failing on the coverage report uploading to CodeCov:

```
->  Pinging Codecov
https://codecov.io/upload/v4?package=bitrise-step-20201116-eea08d9&token=secret&branch=issue-1241&commit=e2b14f228bca360cdeecb879f8e98d5cec718493&build=6537&build_url=https%3A%2F%2Fapp.bitrise.io%2Fbuild%2Fde0272a08fc8d1d2&name=&tag=&slug=mozilla-lockwise%2Flockwise-android&service=bitrise&flags=&pr=1242&job=&cmd_args=Q,Z
HTTP 400
Please provide the repository token to upload reports via `-t :repository-token`
```

**Comment by jonalmeida** [comment]
Ah ha, I was wrong. It was the android-lint task that was failing and I didn't see it.

**Comment by jonalmeida** [comment]
Replacing with https://github.com/mozilla-lockwise/lockwise-android/pull/1243

**Review by jhugman — COMMENTED** [review]
This looks fine, though I think I'd've prefered to see the `requireView` replacements in a different PR. This accounted for 15 /37 files.

Thank you @jonalmeida !

**Pull request closed without merging**
