### PR TITLE
907 fix ui tests

### LINKED ISSUE #907: [UITests] Fix failing UITests after recent commits
### Vision statement / What / Requirements
Latest scheduled build on [Bitrise](https://app.bitrise.io/build/94f9d6550c714f5a#?tab=log) is failing due to [two tests](https://addons-testing.bitrise.io/builds/94f9d6550c714f5a/testreport/ftl/testsuite/0/testcases?status=failed):
-testSettings
-testDisconnectDisclaimer

PR with a fix coming soon

### PR DESCRIPTION
**Pull request by isabelrios**
Fixes #907 

Tests were failing due to routing issues. This PR tries to fix them

### CODE REVIEW

**Comment by isabelrios** [comment]
Most of the tests are working now after adding the routes (hope the new ones are correct 🙈). See [Bitrise logs](https://addons-testing.bitrise.io/builds/61ae4df19c47cdfe/testreport/ftl/testsuite/0/testcases?status=failed). 

There are 4 tests though, the complete `OnboardingTest`test suite which is failing.

The error is `Error performing 'single click' on view with id: mozilla.lockbox:id/buttonGetStarted'`
Full log is here: 
[singleClickError.docx](https://github.com/mozilla-lockwise/lockwise-android/files/3581383/singleClickError.docx)

@eliserichards I would need your help here, trying to understand why those tests do not work if they are calling navigator methods used in previous successful tests...I have to be missing something...I tried some solutions I read, but no success yet, so if you have any clue, please let me know! Thanks!!!

**Comment by isabelrios** [comment]
@eliserichards Could it be due to a route issue? these tests fail because they first call `navigator.gotoFxALogin` all the other tests start going through `gotoItemList` ... which seems a little bit different:
```
fun gotoItemList(goManually: Boolean = false) {
        if (goManually) {
            bypassOnboarding()
        } else {
            Dispatcher.shared.dispatch(LifecycleAction.UseTestData)
            log.info("blocking for the routes")
            // block until onboarding
            // tap skip
            blockUntil(RouteStore.shared.routes, RouteAction.ItemList)
        }
        checkAtItemList()
    }
```

**Comment by eliserichards** [comment]
Maybe try calling `resetApp()` first? And make sure that the welcome screen exists? :/

**Comment by isabelrios** [comment]
> Maybe try calling resetApp() first? And make sure that the welcome screen exists? :/

That does not work :( 

> It also could have something to do with that blockUntil line. Maybe the test just hasn't arrived at the correct screen yet?

That's my feeling...although the screen is shown nothing on that screen is seen (`checkAtWelcome` and ` tapGetStarted() ` fail). I have tried different options to do something similar to the Dispatch and Block part as above but with no success so far. Using different `LifecycleAction`and `Route.Action`
 I think I need your help for a better understanding of this new routing implementation...
Thanks!

**Comment by isabelrios** [comment]
@eliserichards I was finally able to fix the tests! All of them are green again on [Bitrise](https://addons-testing.bitrise.io/builds/d1c596fb89caf721/summary?status=passed)

The issue was that `buttonGetStarted` has to be changed to `buttonGetStartedManually` . After looking at the commits introducing changes and failing the tests, I saw this change and that was the issue. The `single click`error was very confusing and did not look like the issue was about an id... 🤦‍♀

**Comment by eliserichards** [comment]
That's awesome! I totally missed that too. I'm so glad you were able to get it to green! :D

**Pull request merged**
