### PR TITLE
639: Stop using `org.mozilla.appservices` Gradle plugin.

### LINKED ISSUE #639: Stop using `org.mozilla.appservices` Gradle plugin
The Application Services team has not found the `org.mozilla.appservices` Gradle plugin to be a good use of resources.  It's tricky to [support multiple Android-Gradle plugin versions](https://github.com/mozilla/application-services/issues/652) and has been a bottleneck for consumers.  The plan of record -- see https://github.com/mozilla/application-services/pull/921 -- is to push megazord substitutions out to the edges (to consumers) and potentially consolidate in the future.

This unwinds #352.

### PR DESCRIPTION
**Pull request by ncalexan**
This sets up "megazord substitutions" just like the Gradle plugin did,
but manually.  The appservices version and megazord definition will
need to be updated when the Android Components version advances, but
at that time you should see build bustage (and not only runtime
bustage).  When that time comes you should be able to clone the
megazord definitions from other consumers like Fenix and/or the
Reference Browser.

The needed dependencies are fetched from the existing
`maven.mozilla.org` repository.

This unwinds #352.

Fixes #639 

_(**Required**: this reference (one or many) will be closed upon merge. Ideally it has the acceptance criteria and designs for features or fixes related to the work in this Pull Request.)_

Connected to #352.

_(Optional: other issues or pull requests related to this, but merging should not close it)_

## Testing and Review Notes

_(**Required**: steps to take to confirm this works as expected or other guidance for code, UX, and any other reviewers)_

If this passes device tests in automation and some minimal local testing (i.e., the app starts), then it's probably good to go.

## Screenshots or Videos

_(Optional: to clearly demonstrate the feature or fix to help with testing and reviews)_

## To Do

- add “WIP” to the PR title if pushing up but not complete nor ready for review
- [ ] double check the original issue to confirm it is fully satisfied
- [ ] add testing notes and screenshots in PR description to help guide reviewers
- [ ] add unit tests
  - optional: consider adding instrumentation (integration/UI) tests
- consider running this branch in a debug simulator and check for memory leak notifications or any warnings
- [ ] request the "UX" team perform a design review (if/when applicable)
- [ ] make sure CI builds are passing (e.g.: fix lint and other errors)
- [ ] check on the [accessibility](https://mozilla-lockbox.github.io/lockbox-android/accessibility/) of any added UI

### CODE REVIEW

**Comment by devinreams** [comment]
Still failing based on gradle but I can't fully understand why. Does someone else understand why?

**Comment by sashei** [comment]
@ncalexan do we need to include the `mozilla-app-services` version in our properties? or is that built in to this megazord change?

**Comment by ncalexan** [comment]
> @ncalexan do we need to include the `mozilla-app-services` version in our properties? or is that built in to this megazord change?

Yes, this was dropped by a bad merge of `master` into this branch.  (Just FYI: having other people merge into a work-in-progress branch is not a flow that I'm used to on GH.  I almost always want to rebase my work onto `master` as mainline advances, partly to avoid situations like this.)

But that bad merge reveals a legitimate need for rebasing, which this also addresses.  Let's see how it fares in automation.

**Comment by ncalexan** [comment]
@devinreams I couldn't figure out how to extract an APK from the bitrise automation for local testing.  Can you do that local testing, just to make sure we're not obviously busted?  Alternately, if bitrise runs basically _any_ on-device tests that start the App and exercise any native functionality, we're probably good to go.

**Comment by devinreams** [comment]
>Yes, this was dropped by a bad merge of master into this branch.

Thanks and sorry for that, we were trying to keep it up to date and running against the latest ourselves but obviously made a wrong call along the way.

>I couldn't figure out how to extract an APK from the bitrise automation for local testing. Can you do that local testing, just to make sure we're not obviously busted?

Here's a debug APK anyone can access and install (3887):
https://app.bitrise.io/artifact/15370932/p/e9cb1bbdf91d1b165d52a913494d7fd1

**Comment by ncalexan** [comment]
> I did a quick "smoke test" of build 3887 and ran it, signed in, synced, signed out, signed back in. All good here 👍

Beautiful.

> Thanks @ncalexan

yw!  Thanks for doing the final tests and working with it locally -- much appreciated.

**Pull request merged**
