### PR TITLE
Import strings from android-l10n and remove translation warnings from linting

### PR DESCRIPTION
**Pull request by Pike**
State: mozilla-l10n/android-l10n@4e63500774950306eb3930ec1c1ba9c25d837370

Complete localization for de, fr, it. No update for Spanish yet.

These might not be the final version of the translations, as they didn't have any on-device testing yet.

Can we land these to get testing on a nightly build w/out affecting the May release?

CC @Delphine

### CODE REVIEW

**Comment by devinreams** [comment]
The failures are OK and due to linting finding missing strings:

```
  
  The first 3 errors (out of 7) were:
  /bitrise/src/app/src/main/res/values/non_localizable_strings.xml:12: Error: "empty_string" is not translated in "de" (German), "it" (Italian), "fr" (French) [MissingTranslation]
      <string name="empty_string"></string>
              ~~~~~~~~~~~~~~~~~~~
  /bitrise/src/app/src/main/res/values/non_localizable_strings.xml:14: Error: "empty_space" is not translated in "de" (German), "it" (Italian), "fr" (French) [MissingTranslation]
      <string name="empty_space">\u0020</string>
              ~~~~~~~~~~~~~~~~~~
  /bitrise/src/app/src/main/res/values/non_localizable_strings.xml:18: Error: "placeholder_skip_fxa" is not translated in "de" (German), "it" (Italian), "fr" (French) [MissingTranslation]
      <string name="placeholder_skip_fxa">Use test data</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I will see about suppressing these...

But also spotted:

`../../src/main/res/values-it/strings.xml:49: Replace "..." with ellipsis character (…, &#8230;) ?`

Here is a Debug build that can be loaded and run on a device:
https://app.bitrise.io/artifact/15354403/p/380926c4e8da960787829b04739dcf2a

**Comment by Pike** [comment]
Left a suggestion for that in pontoon, https://pontoon.mozilla.org/it/android-l10n/mozilla-lockwise/lockwise-android/app/src/main/res/values/strings.xml/?search=...&string=198638

**Comment by devinreams** [comment]
I also successfully installed this debug build and switched language to German (and back to English):

image

If the lint fixes get this green then I'll merge. If not, I may back them out and then do a separate PR to test out what's needed for linting to be OK. 🤞

**Comment by devinreams** [comment]
>>`../../src/main/res/values-it/strings.xml:49: Replace "..." with ellipsis character (…, &#8230;) ?`

>Left a suggestion for that in pontoon, https://pontoon.mozilla.org/it/android-l10n/mozilla-lockwise/lockwise-android/app/src/main/res/values/strings.xml/?search=...&string=198638

@Pike do you mind if we make that change in the it translation directly, thus assuming it will come across in a future translation?

I'd rather not "ignore" it from the rules nor add this exception to our baseline exceptions report. But really do like having that check in place. 😏

**Comment by Pike** [comment]
Re ellipsis, this is tricky, I haven't found a way to do this right yet. The problem with the linters is that that we don't see their results back in Pontoon.

That things break the build w/out a need is hard on a system that's trying to make this smooth. In particular when we talk about automated commits for the l10n imports, it's going to be tedious trying to enforce linting results on the android w/out having them reflected on the pontoon side.

**Pull request merged**
