### PR TITLE
Create strings.xml for Vietnamese language

### PR DESCRIPTION
**Pull request by hnptuyen**
Requires #869 

New Language: Vietnamese

I added new values strings that translated to Vietnamese based on latest version of default strings in English.

### CODE REVIEW

**Comment by Delphine** [comment]
Thanks for your contribution. We're working off of Pontoon for localizations, not from this repo. Please do not merge this.
I'll see about copying back this work into our repo soon. Otherwise, some copy/pasting into Pontoon will have to be involved. I also need to get in touch with the current localization community

**Comment by Delphine** [comment]
Got in touch with the main contributors and manager of Vietnamese locale.
@hnptuyen: in the meantime, if you'd like to check out Pontoon and create an account there, here is the documentation https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html

**Comment by hnptuyen** [comment]
> 
> 
> Got in touch with the main contributors and manager of Vietnamese locale.
> @hnptuyen: in the meantime, if you'd like to check out Pontoon and create an account there, here is the documentation https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html
> Please also reach out to me by email (delphine at mozilla dot com) so I can introduce you to the community and get you all set up :)
@Delphine: I had one already, just awaiting for you push the project on Pontoon and then I will update on the translation.

**Comment by Delphine** [comment]
Closing this as I've taken care of things in https://github.com/mozilla-l10n/android-l10n/pull/67
thanks!

**Comment by Delphine** [comment]
@hnptuyen: Could you please send me an email (delphine at mozilla dot com) so I can introduce you to the Vietnamese localizers? thanks

**Pull request closed without merging**
