### PR TITLE
Import strings from android-l10n

### PR DESCRIPTION
**Pull request by Pike**
State: mozilla-l10n/android-l10n@6d2fe8331a703e7f46050b93ee4db4812af36095

### CODE REVIEW

**Comment by eliserichards** [comment]
The `sync_timeout` strings have been removed as part of #791, so they should not be re-added here @Pike

**Comment by Pike** [comment]
> The `sync_timeout` strings have been removed as part of #791, so they should not be re-added here @Pike

We merged that in https://github.com/mozilla-l10n/android-l10n/pull/75/files, which isn't part of this import and will only be impacted if we force-sync from Pontoon to android-l10n.

CC @Delphine

**Comment by Pike** [comment]
> Can we force sync so that we have the correct strings @Pike @Delphine?

I ended up removing them manually on the android-l10n repo, which pontoon syncs from. force-sync didn't end up doing what we had hoped for.

**Comment by Pike** [comment]
Updated the PR.

**Pull request merged**
